### ISSUE TITLE
Dedicated Server Crash

### ISSUE THREAD

**Issue by kreezxil** [Malkierian/PlasmaCraft#30]
http://pastebin.com/gmzC1SvZ

**Comment by Kenshij** [comment]
I have the same error. The Client launches without error, but the the server shows java.lang.ClassNotFoundException: com.malkierian.plasmacraft.common.CommonProxy

So when i look into your code the Class CommonProxy is under com.malkierian.plasmacraft.core.CommonProxy. I think somewhere were server code is loaded the class is false included.
