### ISSUE TITLE
Ores in the Plasmificator won't smelt

### ISSUE THREAD

**Issue by Umbrakinetic** [Malkierian/PlasmaCraft#32]
I put in the fuel, I put in the ore, aaaaand... Nothin'.

**Comment by Malkierian** [comment]
What ore?  The plasmificator isn't supposed to smelt things like iron ore or lead ore.  You put those in the furnace to get the ingots and then use the lead ingots to make plasma bars.

**Comment by Umbrakinetic** [comment]
I mean, you can't smelt the ores like radonite or netherflow into goop. Or is that what you mean?

**Comment by Umbrakinetic** [comment]
I suppose it would be more accurate to say substances that don't spawn as liquid as an example; netherflow spawns as a fluid.
