### ISSUE TITLE
Smelting Problems

### ISSUE THREAD

**Issue by SNake57575** [Malkierian/PlasmaCraft#33]
Plasmacraft Ores are not smelting in the Plasmificator and things that do smelt (Goop and vials) if there is more then one item in the stack to smelt one is smelted and the others disappear (Including vials)

**Comment by Umbrakinetic** [comment]
I think Malkierian's dead.

**Comment by Umbrakinetic** [comment]
HEY MALKIERIAN, ARE YOU DEAD?

**Comment by UntouchedWagons** [comment]
A user on the FTB subreddit asked if anyone would be willing to take a look at the mod and I obliged. I'm currently working now but I should have some time later today to take a look at the mod.

**Comment by Umbrakinetic** [comment]
That was me :3 thank you for helping!

**Comment by Malkierian** [comment]
@UntouchedWagons If you decide to update it, go ahead and make a pull request for now, I'll post an updated release when you're done with credit.  If you're so inclined afterward, I'll add you to the contributors.

@Umbrakinetic No, not dead, just really busy and didn't really have any desire to work on the mod.

**Comment by Malkierian** [comment]
@UntouchedWagons In fact, if you want to take over, I'll even add you to the MinecraftForge account so you can post your own updates.  Just let me know.

**Comment by UntouchedWagons** [comment]
So far I've touched pretty much every file by redoing most of the file structure. So I don't know how well a pull request would respond to that.

**Comment by Malkierian** [comment]
It would probably take it as a full rework, honestly.  It's not all that important as far as the repos are concerned, I just figured it would be nice to keep it all in one place still.

**Comment by UntouchedWagons** [comment]
Could you add me as a member on CurseForge? I have a release ready and I want to post it tomorrow to the FTB subreddit.

**Comment by Malkierian** [comment]
Yeah, sure, what's your username on there?

**Comment by UntouchedWagons** [comment]
UntouchedWagons
